name = "workers-contact-form"
type = "javascript"

account_id = ""
workers_dev = true
compatibility_date = "2022-02-22"

[vars]
AIRTABLE_BASE_ID = "exampleBaseId"
AIRTABLE_TABLE_NAME = "Form Submissions"
AIRTABLE_API_KEY = ""
